name: ZITRONE on The Grid
favicon: null
layout_spectrum: 0.5510591566562653
typography_spectrum: 0.95331
title: ZITRONE on The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2132e'
    - '#f6f2f1'
    - '#c2c0c3'
    - '#935e5d'
    - '#d89190'
  brandStrength: 0.875
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
