typography_spectrum: 0.48226
content_rating:
  adult: false
color:
  brandColors:
    - '#949b55'
    - '#c52226'
    - '#ffffff'
    - '#0e2719'
    - '#167c41'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.27907
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Romano Studer
  email: romano.studer@zitrone.com.au
  url: www.zitrone.com.au
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dd4acc9f-c01c-45a4-8f95-3a8482991f18.png
name: ZITRONE on The Grid
cta:
  domain: null
  bucket: null
  version: null
style: taylor
navigation:
  - name: About ZITRONE
    id: 8c5a3cf4-3065-4470-99fa-35777e91bee3
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a977e594-efc2-48dd-84f9-23e11767473f.png
title: 'GRAPHICS FOR WEB AND PRINT, FAST AND BRILLIANT'
purpose: []
