name: ZITRONE on The Grid
favicon: null
layout_spectrum: 0.27907
typography_spectrum: 0.48226
title: ZITRONE on The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#949b55'
    - '#c52226'
    - '#ffffff'
    - '#0e2719'
    - '#167c41'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
