name: ZITRONE on The Grid
favicon: null
layout_spectrum: 0.5510591566562653
typography_spectrum: 0.40669264690950513
title: ZITRONE on The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdd030'
    - '#000000'
    - '#ffffff'
    - '#474749'
    - '#00b1ed'
  brandStrength: 0.875
  lightness: 0.762335061095655
  saturation: 0.5394579579588026
  rhythmicContrast: 0.7631267353426665
purpose: []
